#!/usr/bin/env python3
"""
modeling_pipeline.py
=====================
Complete five-stage photometric stereo pipeline for 3D scroll modeling.

This is the "Modeling" stage of the integrated Papyrus app (see ../../run.py).
It reads the raw scroll photographs from the active scan folder (set by run.py
via PAPYRUS_SCROLL_DIR) and the calibration shots from backend/calibration/, and
writes texture maps to the render-ready output folder, ready for the Rendering
stage to turn into a textured 3D model.

  Stage 0 - Alpha Mask Generation
    Uses a pretrained ML segmentation model (rembg or SAM2) to isolate the
    scroll from the background, producing the binary AlphaMask used by all
    subsequent stages.

  Stage 1 - Lighting Calibration
    Corrects vignetting and per-light illumination falloff using photos of flat
    copy paper, producing corrected scroll images that behave as if lit by
    uniform, infinitely distant lights with a perfect lens.

  Stage 2 - Core Maps (Normal, Diffuse, Specular, Roughness)
    Derives the normal map from the calibrated cross-polarised images using
    a simple gradient approach.  Also computes the diffuse, specular, and
    roughness maps that the renderer needs.  The roughness map is derived
    from the specular map without inversion: papyrus fibres depolarise
    light strongly (high co-cross signal) -> high roughness (matte);
    ink absorbs strongly (low co-cross) -> floored at 0.6 to avoid a
    mirror-smooth appearance.

  Stage 3 - Height Map Generation
    Runs photometric stereo on the calibrated images to recover surface normals,
    then integrates them into height maps via weighted Frankot-Chellappa.
    Six methods are computed (cross-pol, co-pol, specular component, 8-light
    combined, per-RGB-channel, plus integration of the Stage 2 normal map).

  Stage 4 - Prep for Rendering
    Rotates all maps 90° counter-clockwise and pads spatial dimensions to the
    nearest power of two, as required by most real-time renderers.

─────────────────────────────────────────────────────────────────────────────
DIRECTORY LAYOUT - place your files here before running:
─────────────────────────────────────────────────────────────────────────────

  SCROLL_DIR             ← the scroll scans to process: allLight.tiff +
      allLight.tiff            the 8 directional TIFFs. Set by run.py via the
      nco.tiff  sco.tiff       PAPYRUS_SCROLL_DIR env var (a data/<timestamp>/
      eco.tiff  wco.tiff       folder); falls back to the path below when run
      ncross.tiff  scross.tiff   standalone.
      ecross.tiff  wcross.tiff

  ../calibration/        ← same filenames shot on flat copy paper (no scroll),
      nco.tiff  ncross.tiff      in backend/calibration/
      sco.tiff  scross.tiff
      eco.tiff  ecross.tiff
      wco.tiff  wcross.tiff
      allLight.tiff                                     (sanity check only)

  reference_maps/        ← next to this script (backend/modeling/); holds the
      AlphaMask.tiff         AlphaMask generated by Stage 0 (or placed manually)

─────────────────────────────────────────────────────────────────────────────
OUTPUTS WRITTEN BY THIS SCRIPT (into output/ next to this file):
─────────────────────────────────────────────────────────────────────────────

  output/
    1_calibrated/        ← Stage 1: illumination-corrected images
      nco_cal.tiff  ncross_cal.tiff  sco_cal.tiff  scross_cal.tiff
      eco_cal.tiff  ecross_cal.tiff  wco_cal.tiff  wcross_cal.tiff

    2_maps/              ← Stage 2: normal, diffuse, specular, and roughness maps
      NormalMap_Cal.tiff
      DiffuseMap_Cal.tiff
      SpecularMap_Cal.tiff
      SpecularMap_Cal_stretched.tiff
      RoughnessMap_Cal.tiff

    3_height_maps/       ← Stage 3: height maps from six photometric stereo methods
      normalmap_cal_weighted_frankot_u16.tiff
      cross_ps_theta36.98_weighted_frankot_u16.tiff
      co_ps_theta36.98_weighted_frankot_u16.tiff
      specular_component_theta36.98_weighted_frankot_u16.tiff
      combined_8light_theta36.98_weighted_frankot_u16.tiff   ← fed into Stage 4
      cross_ps_channelR/G/B_theta36.98_weighted_frankot_u16.tiff

    4_render_ready/      ← Stage 4: rotated + power-of-two padded, ready for renderer
      AlphaMask_render.tiff
      HeightMap_render.tiff
      DiffuseMap_render.tiff
      NormalMap_render.tiff
      SpecularMap_render.tiff
      RoughnessMap_render.tiff

  run.py's "Build 3D Model" step copies output/4_render_ready/*_render.tiff
  into ../rendering/public/textures/ for the Three.js viewer.

─────────────────────────────────────────────────────────────────────────────
Coordinate convention (pixel space):
  x = column direction (rightward)
  y = row direction (downward)
  z = toward camera (out of image plane)

  North = Left of image  ->  N light direction: (-cos θ,  0, sin θ)
  South = Right          ->  S:                 (+cos θ,  0, sin θ)
  East  = Top            ->  E:                 ( 0, -cos θ, sin θ)
  West  = Bottom         ->  W:                 ( 0, +cos θ, sin θ)
─────────────────────────────────────────────────────────────────────────────
"""

import json
import os
import sys
import numpy as np
import cv2
import tifffile
from PIL import Image
from pathlib import Path
from scipy.ndimage import gaussian_filter

import color_correction as cc


# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION  -  edit these values to match your setup
# ═══════════════════════════════════════════════════════════════════════════════

ROOT     = Path(__file__).resolve().parent   # .../integrated/backend/modeling
APP_ROOT = ROOT.parent.parent                # .../integrated

# ── Input folders (shared across the whole integrated app) ────────────────────
# SCROLL_DIR and RENDER_OUT can be redirected by run.py (per "active working
# folder") via the PAPYRUS_SCROLL_DIR / PAPYRUS_RENDER_OUT environment variables;
# when unset they fall back to the app defaults so the pipeline still runs
# standalone.
SCROLL_DIR = Path(os.environ.get("PAPYRUS_SCROLL_DIR")
                  or APP_ROOT / "scroll_images")  # raw directional-light TIFFs (standalone fallback)
# Calibration (copy-paper TIFFs + the colour chart + the fitted ccm.json) is
# resolved per scan set: $PAPYRUS_CAL_DIR, else <scroll>/cal, else the shared
# <scroll>/../cal (which is what lets side1/ and side2/ share one set), else the
# global backend/calibration/. Calibration is zoom-specific -- the flat-field
# envelope is a per-pixel spatial fit and apply_correction hard-errors on a
# shape mismatch -- so keeping it beside the scan is what keeps an old scan
# reprocessable later.
CAL_DIR    = cc.resolve_cal_dir(SCROLL_DIR, ROOT.parent / "calibration")
MASKS_DIR  = ROOT / "reference_maps"   # AlphaMask.tiff (generated by Stage 0) lives here

# ── Output folders ─────────────────────────────────────────────────────────────
CAL_OUT    = ROOT / "output" / "1_calibrated"   # illumination-corrected images
MAPS_OUT   = ROOT / "output" / "2_maps"         # normal, diffuse, specular maps
HM_OUT     = ROOT / "output" / "3_height_maps"  # photometric stereo height maps
RENDER_OUT = Path(os.environ.get("PAPYRUS_RENDER_OUT")
                  or ROOT / "output" / "4_render_ready")  # rotated + padded, renderer-ready

# ── Stage 0: Alpha Mask parameters ────────────────────────────────────────────
# Backend choices: "rembg" (default, CPU/CUDA via ONNX) or "sam2" (higher quality, ~900 MB)
MASK_BACKEND    = "rembg"
# rembg model choices: "birefnet-general" (best), "u2net" (fastest), "isnet-general-use"
MASK_MODEL      = "birefnet-general"
# Source image to segment - allLight gives the most uniform illumination for masking
MASK_SOURCE_IMG = "allLight.tiff"
# Expand mask edges outward to recover thin ink strokes near the fragment border
MASK_DILATE_PX  = 0

# ── Stage 1: Calibration parameters ───────────────────────────────────────────
# Gaussian blur applied to copy-paper images before using them as correction
# envelopes.  Must be large enough to erase paper grain while keeping the slow
# illumination gradient.  200 px is appropriate for ~5 Mpx images.
SMOOTH_SIGMA = 200.0

# Stage 1 works in LINEAR light and its flat-field divide legitimately produces
# values above 1.0 (a surface brighter than the copy-paper reference, or any
# specular highlight).  The old code clipped those away, which quietly destroyed
# the co-cross specular signal -- exactly the pixels Stage 2 needs.  Instead the
# calibrated images are stored as value/headroom in uint16 (float TIFFs are not
# an option: cv2 writes them as SGILOG, which tifffile cannot read at all).
#
# The headroom is DERIVED from the data rather than fixed, because how far above
# 1.0 the divide reaches depends entirely on how well exposed the calibration
# set is.  On the current, badly over-exposed copy-paper set the west frames
# reach 9.3; on a properly exposed set it should settle near 4.  A fixed
# constant would either clip the former or waste bits on the latter.  Set
# CAL_HEADROOM to a float to pin it instead.
#
# Cost is log2(headroom) bits: ~2 at 4.0, ~3.3 at 10.0, leaving 13-14 of the 16
# -- still far more than the 8 bits Stage 3 used to run on.  The value actually
# used is recorded in output/1_calibrated/stage1_info.json and read back by
# every downstream loader, so the two can never drift apart.
CAL_HEADROOM            = None    # None = derive per run; or pin to e.g. 4.0
CAL_HEADROOM_PERCENTILE = 99.99   # clip at most this fraction of pixels
CAL_HEADROOM_MIN        = 1.0
CAL_HEADROOM_MAX        = 16.0    # refuse to spend more than 4 bits on headroom

# Fraction of a calibration frame allowed to be at/near full scale before Stage 1
# complains. A blown-out copy-paper shot makes illumination_envelope fit a
# flat-topped envelope, so the flat-field silently under-corrects in the middle
# of the frame and any colour matrix fitted against it inherits the error.
CAL_CLIP_WARN_FRAC = 0.001

# Apply the fitted ColorChecker correction at the end of Stage 1. Set False to
# process with an identity correction (useful for A/B against older output).
COLOR_CORRECTION = True

# ── Stage 2: Specular map parameters ──────────────────────────────────────────
SPECULAR_BOOST = 3

# ── Stage 3: Height map parameters ────────────────────────────────────────────
# Physical elevation angle of each directional light above the horizontal plane.
THETA = 36.98

# ── The 8 directional-light image filenames ────────────────────────────────────
LIGHT_IMAGES = [
    "nco.tiff",     "ncross.tiff",
    "sco.tiff",     "scross.tiff",
    "eco.tiff",     "ecross.tiff",
    "wco.tiff",     "wcross.tiff",
]


# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 0 - ALPHA MASK GENERATION
# ═══════════════════════════════════════════════════════════════════════════════
#
# WHY ML SEGMENTATION:
#   The scroll fragment has irregular edges with thin, wispy papyrus fibres.
#   A simple brightness threshold misclassifies dark ink areas inside the
#   fragment as background, and bright background areas as foreground.  A
#   pretrained segmentation model handles these edge cases far more robustly.
#
# Runs on every full pipeline execution by default, regenerating
# reference_maps/AlphaMask.tiff (next to this script) from MASK_SOURCE_IMG via
# the configured ML backend (see MASK_BACKEND/MASK_MODEL above).
# Set to True to skip Stage 0 and reuse an existing AlphaMask.tiff instead.
SKIP_MASK_GENERATION = False

def _cuda_available() -> bool:
    """Check whether a CUDA-capable GPU is available."""
    try:
        import torch
        return torch.cuda.is_available()
    except ImportError:
        return False


def _postprocess_mask(mask: np.ndarray, dilate_px: int = 0) -> np.ndarray:
    """
    Clean up a raw model mask:
      - Binarise to hard 0/255 (eliminates soft-edge uncertainty at boundaries)
      - Optionally dilate to recover fine ink details near the fragment edge
    """
    _, mask = cv2.threshold(mask, 127, 255, cv2.THRESH_BINARY)
    if dilate_px > 0:
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (dilate_px * 2 + 1,) * 2)
        mask   = cv2.dilate(mask, kernel)
    return mask


def _run_rembg(image_path: Path, model_name: str) -> np.ndarray:
    """
    Segment with rembg (ONNX-based, multiple lightweight models).

    Explicitly passes the provider list so CUDA is used when available -
    rembg otherwise silently falls back to CPU even when rembg[gpu] is installed.

    Returns uint8 grayscale mask: 255 = foreground, 0 = background.
    """
    try:
        from rembg import remove, new_session
        import onnxruntime as ort
    except ImportError:
        print("  ERROR: rembg is not installed.")
        print("    Install:  pip install rembg       (CPU only)")
        print("              pip install rembg[gpu]  (with CUDA)")
        sys.exit(1)

    available = ort.get_available_providers()
    if "CUDAExecutionProvider" in available:
        providers    = ["CUDAExecutionProvider", "CPUExecutionProvider"]
        device_label = "CUDA"
    else:
        providers    = ["CPUExecutionProvider"]
        device_label = "CPU (CUDAExecutionProvider not found in onnxruntime)"

    print(f"  Device  : {device_label}")
    print(f"  Loading rembg session with model '{model_name}'...")
    print("  (Model weights will download automatically on first run.)")

    session = new_session(model_name, providers=providers)

    print(f"  Running inference on '{image_path.name}'...")
    # Build rembg's input explicitly rather than via Image.open(). Two reasons:
    #   1. PIL opens a 16-bit TIFF as its HIGH BYTE only, so what rembg saw was
    #      always an 8-bit truncation;
    #   2. more importantly, that truncation is of whatever encoding is on disk.
    #      Linear TIFFs have a median around 0.13 against 0.34 for BT.709, so
    #      feeding them straight in hands the segmentation model a very dark
    #      image and quality changes silently with the capture flags.
    # Decoding to linear and re-encoding to sRGB gives rembg a consistent,
    # display-referred image no matter how the capture was made.
    enc     = cc.read_capture_info(image_path.parent)
    linear  = cc.load_linear01(image_path, enc)
    display = (np.clip(cc.srgb_encode(linear), 0.0, 1.0) * 255).astype(np.uint8)
    if display.ndim == 2:
        display = np.stack([display] * 3, axis=-1)
    print(f"  Source encoding : {enc.describe()}")
    result = remove(Image.fromarray(display[..., :3], mode="RGB"), session=session)

    # Alpha channel: 255 = foreground (keep), 0 = background (discard)
    return np.array(result)[:, :, 3].astype(np.uint8)


def _run_sam2(image_path: Path) -> np.ndarray:
    """
    Segment with SAM2 using a center-point prompt.

    Assumes the scroll fragment occupies the central region of the frame.
    Adjust point_coords below if the fragment is off-centre.
    Model weights (~900 MB) are cached in ~/.cache/huggingface/ after first run.

    Returns uint8 grayscale mask: 255 = foreground, 0 = background.
    """
    try:
        import torch
        from sam2.sam2_image_predictor import SAM2ImagePredictor
    except ImportError:
        print("  ERROR: sam2 is not installed.")
        print("    Install:  pip install sam2")
        sys.exit(1)

    device = "cuda" if _cuda_available() else "cpu"
    print(f"  Device : {device}")
    print("  Loading SAM2 model (weights download on first run ~900 MB)...")

    predictor = SAM2ImagePredictor.from_pretrained(
        "facebook/sam2.1-hiera-large", device=device
    )

    image_bgr = cv2.imread(str(image_path))
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
    h, w      = image_rgb.shape[:2]

    print(f"  Running SAM2 on '{image_path.name}' ({w}×{h})...")
    print("  Prompt: center point as foreground.")

    point_coords = np.array([[w // 2, h // 2]])
    point_labels = np.array([1])   # 1 = foreground

    with torch.inference_mode(), torch.autocast(device, dtype=torch.bfloat16):
        predictor.set_image(image_rgb)
        masks, scores, _ = predictor.predict(
            point_coords=point_coords,
            point_labels=point_labels,
            multimask_output=True,   # returns 3 candidate masks at different scales
        )

    best_mask = masks[np.argmax(scores)]
    print(f"  Best mask score: {np.max(scores):.3f}")
    return (best_mask * 255).astype(np.uint8)


def run_alpha_mask() -> None:
    """Stage 0: generate AlphaMask.tiff using the configured ML backend."""
    if SKIP_MASK_GENERATION:
        print("\n" + "═" * 62)
        print("  STAGE 0 - ALPHA MASK  [skipped - using existing mask]")
        print("═" * 62)
        return
    print("\n")
    print("  STAGE 0 - ALPHA MASK GENERATION")
    print("\n")
    print(f"  Backend : {MASK_BACKEND}")
    if MASK_BACKEND == "rembg":
        print(f"  Model   : {MASK_MODEL}")
    print(f"  Input   : {MASK_SOURCE_IMG}")
    if MASK_DILATE_PX:
        print(f"  Dilate  : {MASK_DILATE_PX} px")
    print()

    MASKS_DIR.mkdir(parents=True, exist_ok=True)
    source = SCROLL_DIR / MASK_SOURCE_IMG

    if MASK_BACKEND == "rembg":
        raw_mask = _run_rembg(source, MASK_MODEL)
    elif MASK_BACKEND == "sam2":
        raw_mask = _run_sam2(source)
    else:
        raise ValueError(f"Unknown backend '{MASK_BACKEND}'. Choose 'rembg' or 'sam2'.")

    mask     = _postprocess_mask(raw_mask, dilate_px=MASK_DILATE_PX)
    out_path = MASKS_DIR / "AlphaMask.tiff"
    cv2.imwrite(str(out_path), mask)

    print(f"\n  Saved: {out_path}  ({mask.shape[1]}×{mask.shape[0]} px)")
    print("\nStage 0 complete.")


# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 1 - LIGHTING CALIBRATION
# ═══════════════════════════════════════════════════════════════════════════════
#
# WHY CALIBRATION IS NEEDED:
#   The four directional lights sit at a finite distance from the scroll, so
#   each pixel sees a slightly different light angle and intensity compared to
#   the frame centre.  The camera lens also vignettes - darkening toward the
#   edges.  Both effects cause systematic per-pixel brightness biases.
#   Photometric stereo interprets all brightness variation as geometry, so
#   these biases produce false normals that accumulate into large height drift
#   after integration (even when the normal map looks fine visually).
#
# HOW IT WORKS:
#   Copy paper is flat  ->  its normal is (0, 0, 1) everywhere, so any spatial
#   brightness variation in a photo of it is purely due to illumination, not
#   geometry.  We fit a smooth envelope to that variation, then divide each
#   scroll image by its matching envelope.  The result behaves as if captured
#   under uniform, infinitely distant light with a perfect lens.
#
#   The envelope is left white-referenced (NOT normalised to median = 1), so
#   the division also rescales the scroll to reflectance relative to the paper:
#   a white surface reads ~1.0, papyrus reads its true (lower) albedo.  This
#   keeps the calibrated images - and every map derived from them - at a
#   natural brightness instead of the paper's dim single-light median level.

def load16(path: Path) -> np.ndarray:
    """Load a 16-bit TIFF unchanged; raise clearly if the file is missing."""
    img = cv2.imread(str(path), cv2.IMREAD_UNCHANGED)
    if img is None:
        raise FileNotFoundError(f"Cannot load: {path}")
    return img


def illumination_envelope(cal_linear_bgr: np.ndarray) -> np.ndarray:
    """
    Extract the white-referenced illumination envelope from a calibration image.

    Takes LINEAR light (see run_calibration). The BT.709 luminance weights below
    are defined on linear light, so this is the first version where collapsing
    to luminance is actually the quantity it claims to be.

    Steps:
      1. Collapse to luminance.
      2. Large Gaussian blur erases paper grain, keeping only the slow gradient.

    Returns float32 (H, W) equal to the copy paper's own luminance response
    (reflectance x illumination x geometry).  Because the copy paper is a flat,
    near-white reference, dividing a scroll image by this envelope both removes
    the illumination gradient AND rescales to true relative albedo: a white,
    fully-lit surface maps to ~1.0 everywhere, and the scroll reads as its
    reflectance relative to the paper (papyrus / paper).

    NOTE: an earlier version normalised this to median = 1.0.  That preserved
    only the *relative* gradient, so the corrected images stayed pinned to the
    paper's dim single-light median level (~0.29 for white paper under one
    grazing light) - which made every downstream map, and the render, far
    darker than the original photos.  It also scaled each of the four
    directional lights by its own median (0.29 vs 0.37 ...), putting the N/E/S/W
    images on slightly different brightness scales and biasing the normal-map
    gradients.  Referencing to white (below) fixes both.
    """
    f = np.asarray(cal_linear_bgr, dtype=np.float64)

    # Collapse to luminance so one envelope corrects all colour channels equally.
    # Weights are BGR-ordered to match cv2's channel order.
    if f.ndim == 3:
        lum = 0.0722 * f[:, :, 0] + 0.7152 * f[:, :, 1] + 0.2126 * f[:, :, 2]
    else:
        lum = f

    smooth = gaussian_filter(lum, sigma=SMOOTH_SIGMA)

    # Sanity check only - the envelope itself is left in absolute (white-referenced)
    # units so the correction rescales the scroll to relative albedo.
    med = float(np.median(smooth[smooth > 1e-4]))
    if med <= 0:
        raise ValueError("Calibration image appears empty - check the file.")

    return smooth.astype(np.float32)


def apply_correction(scroll_linear: np.ndarray, envelope: np.ndarray) -> np.ndarray:
    """
    Divide a linear scroll image by its illumination envelope.

    Each pixel is divided by the envelope value at that position, compensating
    for vignetting, light falloff, and perspective angle differences.  Because
    the envelope is white-referenced (see illumination_envelope), this also
    rescales the scroll to relative albedo - a white surface -> ~1.0.

    Both sides are LINEAR, so this is genuinely reflectance / reference
    reflectance.  It used to run on gamma-encoded values, where a 2x light
    falloff shows up as a 2^(1/2.222) = 1.37x ratio - i.e. vignetting was only
    ever corrected at roughly 40% strength.

    Returns float32, clamped below at 0 but NOT above: values over 1.0 are real
    (anything brighter than the paper reference, and every specular highlight)
    and the caller stores them via CAL_HEADROOM.  The old [0,1] clip here threw
    away ~20% of every frame.
    """
    s = np.asarray(scroll_linear, dtype=np.float32)
    h, w = s.shape[:2]
    if envelope.shape != (h, w):
        eh, ew = envelope.shape
        raise ValueError(
            f"Calibration envelope shape ({eh}×{ew}) does not match scroll image "
            f"({h}×{w}). The calibration images may need to be rotated to match the "
            f"scroll image orientation - re-run the rotation fix before continuing."
        )
    # Floor is relative to the envelope's own peak rather than an absolute 0.05,
    # which was tuned in the old gamma domain and means something different now.
    # Guards divide-by-zero and runaway noise in corners that got almost no light.
    env = np.maximum(envelope, 0.02 * float(envelope.max()))

    corrected = s / env[:, :, np.newaxis] if s.ndim == 3 else s / env
    return np.maximum(corrected, 0.0).astype(np.float32)


def _warn_if_clipped(img_uint16: np.ndarray, name: str) -> float:
    """Warn when a calibration frame is blown out. Returns the clipped fraction.

    A clipped copy-paper shot makes illumination_envelope fit a flat-topped
    envelope, so the flat-field under-corrects in the brightest part of the
    frame - and any colour matrix fitted against a flat-fielded chart inherits
    that error. Worth shouting about: it is invisible in the output.
    """
    frac = float((img_uint16 >= 65000).mean())
    if frac > CAL_CLIP_WARN_FRAC:
        print(f"  WARNING: {name} is {frac * 100:.1f}% clipped at full scale. "
              "The illumination envelope will be flat-topped there and the "
              "flat-field will under-correct. Re-shoot this calibration set "
              "1-1.5 stops darker (brightest paper pixel <= ~60000).")
    return frac


def run_calibration() -> None:
    """Stage 1: produce illumination-corrected versions of all 8 scroll images."""
    cal_enc  = cc.read_capture_info(CAL_DIR)
    scan_enc = cc.read_capture_info(SCROLL_DIR)
    ccm_path = cc.find_ccm(CAL_DIR)
    if ccm_path and COLOR_CORRECTION:
        correction = cc.ColorCorrection.load(ccm_path)
    else:
        correction = cc.ColorCorrection.identity(scan_enc)
    corr_bgr = correction.as_bgr()

    print("\n")
    print("  STAGE 1 - LIGHTING CALIBRATION")
    print("\n")
    print(f"  Scroll images  : {SCROLL_DIR}")
    print(f"  Calibration    : {CAL_DIR}")
    print(f"  Output         : {CAL_OUT}")
    print(f"  Gaussian sigma : {SMOOTH_SIGMA} px")
    print(f"  Scan encoding  : {scan_enc.describe()}")
    print(f"  Cal  encoding  : {cal_enc.describe()}")
    if ccm_path and COLOR_CORRECTION:
        print(f"  Colour matrix  : {ccm_path.name}  ({correction.summary()})")
    elif not COLOR_CORRECTION:
        print("  Colour matrix  : DISABLED (COLOR_CORRECTION = False)")
    else:
        print(f"  Colour matrix  : none found in {CAL_DIR} - running uncorrected. "
              "Capture a colour chart and fit it to enable colour correction.")
    print("  Headroom       : " + (f"pinned at {CAL_HEADROOM:g}"
                                   if CAL_HEADROOM is not None
                                   else "derived from the data") + "\n")

    if not CAL_DIR.is_dir():
        raise FileNotFoundError(
            f"Calibration folder not found: {CAL_DIR}\n"
            "Create it and place the 9 copy-paper TIFF images inside."
        )

    CAL_OUT.mkdir(parents=True, exist_ok=True)

    # Build one smooth envelope per calibration image.
    #
    # DELIBERATE: the envelope comes from the UNCORRECTED linear paper. The
    # colour fit divides the chart by this same uncorrected envelope, so the
    # fit and the application below live in identical units and the matrix
    # transfers with no scalar bookkeeping. Colour-correcting the paper here
    # would break that invariant silently. See color_correction.py's header.
    print("Building illumination envelopes from copy-paper images...")
    envelopes = {}
    for name in LIGHT_IMAGES:
        raw             = load16(CAL_DIR / name)
        _warn_if_clipped(raw, name)
        lin             = cc.to_linear(raw.astype(np.float32) / 65535.0, cal_enc)
        env             = illumination_envelope(lin)
        envelopes[name] = env
        lo, hi = float(env.min()), float(env.max())
        print(f"  {name:<20s}  range [{lo:.3f}, {hi:.3f}]  "
              f"({hi / max(lo, 1e-6):.2f}× corner-to-centre variation)")

    # allLight envelope is printed for sanity only - not applied to anything
    al_path = CAL_DIR / "allLight.tiff"
    if al_path.exists():
        al_raw = load16(al_path)
        _warn_if_clipped(al_raw, "allLight.tiff")
        al_env = illumination_envelope(
            cc.to_linear(al_raw.astype(np.float32) / 65535.0, cal_enc))
        print(f"  {'allLight.tiff':<20s}  range [{al_env.min():.3f}, "
              f"{al_env.max():.3f}]  (reference only, not applied)")

    def corrected_image(name: str, report: bool = False) -> np.ndarray:
        """Linearise -> flat-field -> colour-correct. The whole of Stage 1."""
        raw = load16(SCROLL_DIR / name)
        if report:
            # Per-CHANNEL, unlike the calibration check: a warm subject under a
            # warm light saturates red long before the image looks bright, and a
            # saturated channel is unrecoverable - no colour matrix can invent
            # the value back. cv2 gives BGR.
            for idx, ch in enumerate("BGR"):
                frac = float((raw[:, :, idx] >= 65000).mean())
                if frac > CAL_CLIP_WARN_FRAC:
                    print(f"    WARNING: {ch} channel is {frac * 100:.1f}% "
                          "saturated in the capture itself. Colour cannot be "
                          "recovered there - re-shoot with less exposure.")
        linear  = cc.to_linear(raw.astype(np.float32) / 65535.0, scan_enc)
        divided = apply_correction(linear, envelopes[name])
        return corr_bgr.apply(divided)   # <- END OF STAGE 1 (identity until fitted)

    # Pass 1: how much headroom does this data actually need? Only scalars are
    # kept, so memory stays flat; the expensive part (the envelopes) is already
    # cached above, making the second read cheap.
    if CAL_HEADROOM is not None:
        headroom = float(CAL_HEADROOM)
        print(f"\nHeadroom pinned to {headroom:g} by configuration.")
    else:
        print(f"\nMeasuring headroom (p{CAL_HEADROOM_PERCENTILE:g} across all "
              "8 images)...")
        peaks = {}
        for name in LIGHT_IMAGES:
            peaks[name] = float(np.percentile(corrected_image(name),
                                              CAL_HEADROOM_PERCENTILE))
        hottest  = max(peaks, key=peaks.get)
        headroom = float(np.clip(np.ceil(max(peaks.values()) * 2) / 2,
                                 CAL_HEADROOM_MIN, CAL_HEADROOM_MAX))
        print(f"  Hottest image: {hottest} (p{CAL_HEADROOM_PERCENTILE:g} = "
              f"{peaks[hottest]:.2f})  ->  headroom {headroom:g} "
              f"({np.log2(headroom):.1f} of 16 bits)")
        if headroom >= CAL_HEADROOM_MAX:
            print(f"  NOTE: hit the {CAL_HEADROOM_MAX:g} cap. This usually means "
                  "the calibration set is over-exposed, which inflates the "
                  "flat-field divide in the dim corners.")

    # Pass 2: write.
    print("\nApplying corrections to scroll images...")
    for name in LIGHT_IMAGES:
        print(f"  {name}")
        corrected = corrected_image(name, report=True)
        over = float((corrected > headroom).mean())
        u16  = (np.clip(corrected / headroom, 0.0, 1.0) * 65535).astype(np.uint16)

        stem, ext = os.path.splitext(name)
        out_path  = CAL_OUT / f"{stem}_cal{ext}"
        cv2.imwrite(str(out_path), u16)
        print(f"    ->  {out_path.name}   "
              f"p50={np.median(corrected):.3f} p99.9={np.percentile(corrected, 99.9):.3f} "
              f"max={corrected.max():.3f}" +
              (f"  [{over * 100:.3f}% clipped]" if over > 1e-6 else ""))

    # Readers must scale by the same headroom, so record it rather than let two
    # copies of the constant drift apart.
    (CAL_OUT / "stage1_info.json").write_text(json.dumps({
        "headroom": headroom,
        "headroom_source": "pinned" if CAL_HEADROOM is not None else "derived",
        "domain": "linear",
        "scan_encoding": scan_enc.kind,
        "cal_encoding": cal_enc.kind,
        "cal_dir": str(CAL_DIR),
        "ccm": str(ccm_path) if (ccm_path and COLOR_CORRECTION) else None,
    }, indent=2))

    print("\nStage 1 complete.")


# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 2 - CORE MAPS  (Normal · Diffuse · Specular)
# ═══════════════════════════════════════════════════════════════════════════════
#
# NORMAL MAP:
#   Cross-polarised images suppress specular highlights, so their brightness
#   variation is mainly diffuse - i.e. driven by surface orientation.  For a
#   Lambertian surface under distant lights, the x-gradient of the surface
#   normal is proportional to the E-W brightness difference, and the
#   y-gradient to the N-S difference.  The z-component follows from the
#   unit-normal constraint: nz = sqrt(1 - nx² - ny²).
#
# DIFFUSE MAP:
#   Averaging all four cross-polarised images cancels directional shading and
#   leaves a clean diffuse albedo image of the scroll surface.
#
# SPECULAR MAP:
#   Subtracting each cross-polarised image from its co-polarised counterpart
#   isolates the specular (ink) component.  Averaging over four directions
#   reduces directional artifacts.

def _stage1_headroom() -> float:
    """The headroom Stage 1 actually used, from its sidecar.

    Read rather than assumed so that re-running a later stage against calibrated
    images produced by a different CAL_HEADROOM cannot silently mis-scale them.
    """
    info_path = CAL_OUT / "stage1_info.json"
    try:
        return float(json.loads(info_path.read_text())["headroom"])
    except (OSError, ValueError, KeyError, TypeError):
        # No sidecar: either Stage 1 predates it or the images were produced
        # elsewhere. 1.0 is the safe reading of "unscaled".
        return float(CAL_HEADROOM) if CAL_HEADROOM is not None else 1.0


def _load_bgr_f32(path: Path) -> np.ndarray:
    """Load a calibrated TIFF as linear BGR float32, headroom restored.

    Stage 1 stores value/headroom to fit its >1.0 linear values into uint16, so
    everything downstream has to multiply back to recover real reflectance.
    """
    img = cv2.imread(str(path), cv2.IMREAD_UNCHANGED)
    if img is None:
        raise FileNotFoundError(f"Could not load: {path}")
    if img.ndim == 2:
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    scale = 255.0 if img.dtype == np.uint8 else 65535.0
    return img.astype(np.float32) / scale * np.float32(_stage1_headroom())


def _bgr_to_luminance(bgr: np.ndarray) -> np.ndarray:
    """Convert BGR float32 image to scalar luminance using BT.709 weights."""
    return (0.0722 * bgr[:, :, 0]
            + 0.7152 * bgr[:, :, 1]
            + 0.2126 * bgr[:, :, 2])


def _encode_normal_uint16(component: np.ndarray) -> np.ndarray:
    """Map a normal component in [-1, 1] to uint16 [0, 65535]."""
    return np.clip(((component + 1.0) / 2.0) * 65535.0, 0, 65535).astype(np.uint16)


def _normalize_to_uint16(arr: np.ndarray, mask: np.ndarray,
                          lo_pct: float = 0.5, hi_pct: float = 99.5) -> np.ndarray:
    """
    Stretch values inside the mask to [0, 65535] using percentile clipping.

    Percentile clipping (default 0.5–99.5) discards extreme outlier pixels
    that would otherwise compress the useful dynamic range.
    Background pixels (outside mask) are set to 0.
    """
    valid  = arr[mask]
    lo     = float(np.percentile(valid, lo_pct))
    hi     = float(np.percentile(valid, hi_pct))
    normed = (arr - lo) / max(hi - lo, 1e-10)
    normed = np.where(mask, np.clip(normed, 0.0, 1.0), 0.0)
    return (normed * 65535).astype(np.uint16)


def run_core_maps() -> None:
    """Stage 2: compute the normal, diffuse, and specular maps."""
    print("\n")
    print("  STAGE 2 - CORE MAPS  (Normal · Diffuse · Specular)")
    print("\n")
    print(f"  Calibrated images : {CAL_OUT}")
    print(f"  Alpha mask        : {MASKS_DIR}")
    print(f"  Output            : {MAPS_OUT}\n")

    MAPS_OUT.mkdir(parents=True, exist_ok=True)

    # Load calibrated cross-polarised images (specular highlights suppressed)
    print("Loading calibrated cross-polarised images...")
    cross_N = _load_bgr_f32(CAL_OUT / "ncross_cal.tiff")
    cross_S = _load_bgr_f32(CAL_OUT / "scross_cal.tiff")
    cross_E = _load_bgr_f32(CAL_OUT / "ecross_cal.tiff")
    cross_W = _load_bgr_f32(CAL_OUT / "wcross_cal.tiff")

    # Load calibrated co-polarised images (specular highlights preserved)
    print("Loading calibrated co-polarised images...")
    co_N = _load_bgr_f32(CAL_OUT / "nco_cal.tiff")
    co_S = _load_bgr_f32(CAL_OUT / "sco_cal.tiff")
    co_E = _load_bgr_f32(CAL_OUT / "eco_cal.tiff")
    co_W = _load_bgr_f32(CAL_OUT / "wco_cal.tiff")

    # Luminance channels from cross-pol images
    L_N = _bgr_to_luminance(cross_N)
    L_S = _bgr_to_luminance(cross_S)
    L_E = _bgr_to_luminance(cross_E)
    L_W = _bgr_to_luminance(cross_W)

    # Load alpha mask
    mask_img  = cv2.imread(str(MASKS_DIR / "AlphaMask.tiff"), cv2.IMREAD_GRAYSCALE)
    if mask_img is None:
        raise FileNotFoundError(f"AlphaMask not found: {MASKS_DIR / 'AlphaMask.tiff'}\n"
                                 "Run Stage 0 first, or place AlphaMask.tiff manually.")
    mask_bool = mask_img > 0

    H_img, W_img = L_N.shape
    print(f"  Image size     : {W_img}×{H_img} px")
    print(f"  Masked pixels  : {mask_bool.sum():,}")

    # ── Normal Map ────────────────────────────────────────────────────────────
    print("\nComputing Normal Map...")
    gx    = (L_E - L_W).astype(np.float32)    # x-gradient from E-W brightness diff
    gy    = (L_N - L_S).astype(np.float32)    # y-gradient from N-S brightness diff
    gz    = np.sqrt(np.clip(1.0 - gx**2 - gy**2, 0.0, None)).astype(np.float32)

    # Zero out background so the mask boundary is clean in the saved TIFF
    nx = np.where(mask_bool, gx, 0.0).astype(np.float32)
    ny = np.where(mask_bool, gy, 0.0).astype(np.float32)
    nz = np.where(mask_bool, gz, 1.0).astype(np.float32)

    # Encode as BGR uint16: Blue=nz, Green=ny, Red=nx
    normal_bgr = np.stack([
        _encode_normal_uint16(nz),
        _encode_normal_uint16(ny),
        _encode_normal_uint16(nx),
    ], axis=2)
    cv2.imwrite(str(MAPS_OUT / "NormalMap_Cal.tiff"), normal_bgr)
    print(f"  Saved NormalMap_Cal.tiff")

    # ── Diffuse Map ───────────────────────────────────────────────────────────
    # Average of all four cross-pol directions; cross-pol removes specular
    # highlights so this is a clean diffuse albedo image.
    print("Computing Diffuse Map...")
    mask_3ch   = mask_bool[:, :, np.newaxis]
    diffuse_16 = (np.clip(
        np.where(mask_3ch, (cross_N + cross_S + cross_E + cross_W) / 4.0, 0.0),
        0.0, 1.0
    ) * 65535).astype(np.uint16)
    cv2.imwrite(str(MAPS_OUT / "DiffuseMap_Cal.tiff"), diffuse_16)
    print(f"  Saved DiffuseMap_Cal.tiff")

    # ── Specular Map ──────────────────────────────────────────────────────────
    # co - cross isolates the specular (ink) component per direction.
    # Negative values are clamped to 0 (specular reflectance can't be negative).
    print("Computing Specular Map...")
    co_L_N = _bgr_to_luminance(co_N)
    co_L_S = _bgr_to_luminance(co_S)
    co_L_E = _bgr_to_luminance(co_E)
    co_L_W = _bgr_to_luminance(co_W)

    specular_avg = np.where(
        mask_bool,
        (np.clip(co_L_N - L_N, 0.0, None) +
         np.clip(co_L_S - L_S, 0.0, None) +
         np.clip(co_L_E - L_E, 0.0, None) +
         np.clip(co_L_W - L_W, 0.0, None)) / 4.0,
        0.0,
    )
    specular_16_stretched = _normalize_to_uint16(specular_avg, mask_bool)
    cv2.imwrite(str(MAPS_OUT / "SpecularMap_Cal_stretched.tiff"), specular_16_stretched)
    print(f"  Saved SpecularMap_Cal_stretched.tiff")

    specular_16 = (np.clip(
        np.where(mask_bool, specular_avg * SPECULAR_BOOST, 0.0), 0.0, 1.0
    ) * 65535).astype(np.uint16)
    cv2.imwrite(str(MAPS_OUT / "SpecularMap_Cal.tiff"), specular_16)
    print(f"  Saved SpecularMap_Cal.tiff (boosted x{SPECULAR_BOOST})")

    # ── Roughness Map ─────────────────────────────────────────────────────────
    # Roughness is the perceptual inverse of specularity.  Normalise the raw
    # specular signal to [0, 1] using its 99.5th-percentile as the ceiling
    # (same clip used by _normalize_to_uint16), then invert.  This gives
    # roughness ≈ 1.0 on plain papyrus and lower values on ink.
    print("Computing Roughness Map...")
    valid_spec = specular_avg[mask_bool]
    spec_hi    = float(np.percentile(valid_spec, 99.5)) if valid_spec.size else 1.0
    spec_norm  = np.clip(specular_avg / max(spec_hi, 1e-10), 0.0, 1.0)
    # specular_avg (co-cross) is low on plain papyrus and high on ink, so
    # spec_norm follows the same pattern. Roughness must move the opposite
    # way: low on ink (shinier), high on papyrus (matte) - hence 1 - spec_norm.
    # The 0.6 floor keeps ink from looking mirror-smooth.
    roughness  = np.where(mask_bool, np.maximum(1.0 - spec_norm, 0.6), 1.0)
    roughness_16 = (roughness * 65535).astype(np.uint16)
    cv2.imwrite(str(MAPS_OUT / "RoughnessMap_Cal.tiff"), roughness_16)
    print(f"  Saved RoughnessMap_Cal.tiff")

    print("\nStage 2 complete.")


# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 3 - HEIGHT MAP GENERATION  (photometric stereo × 6 methods)
# ═══════════════════════════════════════════════════════════════════════════════
#
# HOW PHOTOMETRIC STEREO WORKS:
#   Under the Lambertian model, pixel brightness equals albedo × (L · n).
#   With k images under k different known light directions this gives a k×3
#   linear system for the (scaled) normal at each pixel.  The pseudo-inverse
#   gives the least-squares solution; dividing by its magnitude yields the
#   unit normal.
#
# HOW FRANKOT-CHELLAPPA INTEGRATION WORKS:
#   Given the gradient field (p = dz/dx, q = dz/dy) from the normal field,
#   Frankot-Chellappa recovers height z(x,y) by solving
#   argmin_Z ‖∇Z - (p, q)‖² in the Fourier domain.  This enforces
#   integrability and avoids error accumulation that affects row-by-row
#   integration.  Weighting by the z-component of the normal down-weights
#   grazing-angle normals that are geometrically less reliable.

# NOTE: these loaders read through tifffile, NOT PIL.  PIL opens a 16-bit RGB
# TIFF as mode "RGB" and silently returns the HIGH BYTE only (verified:
# PIL_array == tifffile_array >> 8), so every one of these used to hand
# photometric stereo an 8-bit truncation of 16-bit data.  tifffile returns the
# file's channels in stored order, which is the same RGB order PIL gave, so the
# luminance weights and channel indices below are unchanged - only precision is.

def _load_gray(path: Path) -> np.ndarray:
    """Load a calibrated image as linear float32 luminance, headroom restored.

    Only ever used on Stage 1 output (CAL_OUT/*_cal.tiff), which is stored
    divided by the headroom - hence the multiply back.
    """
    img = tifffile.imread(str(path)).astype(np.float32)
    if img.ndim == 3:
        img = 0.2126 * img[..., 0] + 0.7152 * img[..., 1] + 0.0722 * img[..., 2]
    return img / 65535.0 * np.float32(_stage1_headroom())


def _load_rgb(path: Path) -> np.ndarray:
    """Load an RGB map as float32 in [0, 1].

    NO headroom scaling: this reads NormalMap_Cal.tiff, a Stage 2 output where
    the channels encode a direction over the full [0,1] range, not a Stage 1
    calibrated image.
    """
    return tifffile.imread(str(path)).astype(np.float32) / 65535.0


def _load_mask(path: Path) -> np.ndarray:
    """Load alpha mask as a boolean array (True = scroll pixel).

    AlphaMask.tiff is written by Stage 0 as uint8 0/255, so this threshold is
    against 8-bit levels and needs no rescaling.
    """
    return tifffile.imread(str(path)) > 128


def _save_u16(height: np.ndarray, path: Path, mask: np.ndarray | None = None) -> None:
    """
    Save a height map as uint16 TIFF.

    Valid pixels are mapped to [1, 65535].  Background pixels (outside the
    mask) are set to 0 so they are unambiguously distinguishable from the
    lowest surface point.
    """
    h     = height.copy()
    valid = h[mask] if mask is not None else h.ravel()
    valid = valid[np.isfinite(valid)]
    lo, hi = float(valid.min()), float(valid.max())
    span   = hi - lo if hi > lo else 1.0

    h_u16 = ((h - lo) / span * 65534 + 1).clip(1, 65535).astype(np.uint16)
    if mask is not None:
        h_u16[~mask] = 0

    out_path = path.parent / (path.stem + "_u16.tiff")
    tifffile.imwrite(str(out_path), h_u16, photometric="minisblack")
    print(f"    Saved {out_path.name}")


def decode_normal_map(rgb01: np.ndarray) -> np.ndarray:
    """Convert an RGB normal-map encoding in [0, 1] to unit normals (H, W, 3).

    Takes [0, 1] rather than uint8 levels so it is independent of the source
    bit depth: it previously hardcoded 2.0/255.0 and only survived the 16-bit
    switch because the caller scaled back up by 255 first.
    """
    n  = rgb01.astype(np.float32) * 2.0 - 1.0
    nz = np.clip(n[..., 2], 1e-6, 1.0)
    return n / nz[..., None]


def normals_to_gradients(normals: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Convert surface normals to height-map gradients: p = dz/dx, q = dz/dy."""
    return -normals[..., 0], -normals[..., 1]


def frankot_chellappa(p: np.ndarray, q: np.ndarray) -> np.ndarray:
    """
    Integrate gradient field (p, q) into a height map via Frankot-Chellappa.

    Solves argmin_Z ‖∇Z - (p, q)‖² in the Fourier domain.
    DC component is set to 0 (absolute height offset is arbitrary).
    """
    rows, cols = p.shape
    fx = np.fft.fftfreq(cols)[None, :]
    fy = np.fft.fftfreq(rows)[:, None]

    P, Q = np.fft.fft2(p), np.fft.fft2(q)

    denom       = fx**2 + fy**2
    denom[0, 0] = 1.0   # avoid divide-by-zero at DC; Z[0,0] forced to 0 below

    Z       = (-1j * fx * P - 1j * fy * Q) / (2 * np.pi * denom)
    Z[0, 0] = 0.0

    return np.real(np.fft.ifft2(Z))


def weighted_frankot_chellappa(p: np.ndarray, q: np.ndarray,
                                weights: np.ndarray) -> np.ndarray:
    """Frankot-Chellappa with per-pixel confidence weights on the gradients."""
    return frankot_chellappa(weights * p, weights * q)


def build_light_matrix(theta_deg: float) -> np.ndarray:
    """
    Build the 4×3 matrix of unit light directions for N/S/E/W at elevation theta_deg.

    Each row is a unit vector from the surface toward the light source.
    Sign convention: North = image left (-x), East = image top (-y).
    """
    th   = np.radians(theta_deg)
    c, s = np.cos(th), np.sin(th)
    return np.array([
        [-c,  0,  s],   # North
        [ c,  0,  s],   # South
        [ 0, -c,  s],   # East
        [ 0,  c,  s],   # West
    ], dtype=np.float32)


def photometric_stereo(images: np.ndarray, L: np.ndarray,
                        mask: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """
    Recover surface normals and albedo from k images under k known lights.

    Solves the Lambertian model via pseudo-inverse of L.  Only masked pixels
    are solved; background pixels receive zero normals and zero albedo.

    Returns (normals (H,W,3), albedo (H,W)).
    """
    k, H, W   = images.shape
    I_masked  = images.reshape(k, -1).T[mask.ravel()]

    M              = (np.linalg.pinv(L) @ I_masked.T).T
    albedo_masked  = np.linalg.norm(M, axis=1, keepdims=True).clip(1e-9)
    normals_masked = M / albedo_masked

    normals_flat       = np.zeros((H * W, 3), dtype=np.float32)
    normals_flat[mask.ravel()] = normals_masked.astype(np.float32)
    albedo_flat        = np.zeros(H * W, dtype=np.float32)
    albedo_flat[mask.ravel()] = albedo_masked[:, 0].astype(np.float32)

    return normals_flat.reshape(H, W, 3), albedo_flat.reshape(H, W)


def _ps_to_height(ns: np.ndarray, mask: np.ndarray, label: str) -> None:
    """Normalise a photometric-stereo normal field and save the integrated height map."""
    nz      = np.clip(ns[..., 2], 1e-6, 1.0)
    safe_nz = np.where(mask, nz, 1.0)
    p       = np.where(mask, -ns[..., 0] / safe_nz, 0.0)
    q       = np.where(mask, -ns[..., 1] / safe_nz, 0.0)
    print(f"  Integrating [{label}]...")
    _save_u16(weighted_frankot_chellappa(p, q, weights=nz),
              HM_OUT / f"{label}_weighted_frankot", mask)


def run_height_maps() -> None:
    """Stage 3: photometric stereo -> height maps using six methods."""
    print("\n")
    print("  STAGE 3 - HEIGHT MAP GENERATION")
    print("\n")
    print(f"  Calibrated images : {CAL_OUT}")
    print(f"  Normal map        : {MAPS_OUT}")
    print(f"  Alpha mask        : {MASKS_DIR}")
    print(f"  Output            : {HM_OUT}")
    print(f"  Light elevation   : {THETA}°\n")

    HM_OUT.mkdir(parents=True, exist_ok=True)

    mask = _load_mask(MASKS_DIR / "AlphaMask.tiff")
    L    = build_light_matrix(THETA)

    # ── Method 1: integrate the Stage 2 gradient-based normal map ─────────────
    # Provides a baseline to compare against the photometric stereo results.
    print("Method 1: Integrate from NormalMap_Cal.tiff (Stage 2 output)")
    nm_rgb       = _load_rgb(MAPS_OUT / "NormalMap_Cal.tiff")
    normals_cal  = decode_normal_map(nm_rgb)
    p_cal, q_cal = normals_to_gradients(normals_cal)
    nz_cal       = np.clip(nm_rgb[..., 2] * 2.0 - 1.0, 1e-6, 1.0)
    print("  Integrating [normalmap_cal]...")
    _save_u16(weighted_frankot_chellappa(p_cal, q_cal, nz_cal),
              HM_OUT / "normalmap_cal_weighted_frankot", mask)

    # ── Method 2: photometric stereo from cross-polarised images ─────────────
    # Cross-pol suppresses specular highlights, giving a cleaner diffuse signal.
    print("\nMethod 2: Photometric stereo - cross-polarised")
    I_cross = np.stack([
        _load_gray(CAL_OUT / "ncross_cal.tiff"),
        _load_gray(CAL_OUT / "scross_cal.tiff"),
        _load_gray(CAL_OUT / "ecross_cal.tiff"),
        _load_gray(CAL_OUT / "wcross_cal.tiff"),
    ], axis=0)
    ns_cross, _ = photometric_stereo(I_cross, L, mask)
    _ps_to_height(ns_cross, mask, f"cross_ps_theta{THETA}")

    # ── Method 3: photometric stereo from co-polarised images ────────────────
    # Co-pol preserves specular highlights (ink reflectance), which may carry
    # additional surface information.
    print("\nMethod 3: Photometric stereo - co-polarised")
    I_co = np.stack([
        _load_gray(CAL_OUT / "nco_cal.tiff"),
        _load_gray(CAL_OUT / "sco_cal.tiff"),
        _load_gray(CAL_OUT / "eco_cal.tiff"),
        _load_gray(CAL_OUT / "wco_cal.tiff"),
    ], axis=0)
    ns_co, _ = photometric_stereo(I_co, L, mask)
    _ps_to_height(ns_co, mask, f"co_ps_theta{THETA}")

    # ── Method 4: specular component = co minus cross ─────────────────────────
    # The difference isolates specular (ink) geometry - height variation driven
    # by ink layer relief rather than underlying paper surface texture.
    print("\nMethod 4: Photometric stereo - specular component (co - cross)")
    # Clamp negatives only. The old 1.0 ceiling assumed the inputs topped out at
    # 1.0; with headroom restored they legitimately run higher, and capping here
    # would flatten exactly the bright ink pixels this method exists to measure.
    I_diff     = np.maximum(I_co - I_cross, 0.0)
    ns_diff, _ = photometric_stereo(I_diff, L, mask)
    _ps_to_height(ns_diff, mask, f"specular_component_theta{THETA}")

    # ── Method 5: 8-light combined (co + cross) ───────────────────────────────
    # Stacking both polarisation states doubles the light constraints, improving
    # the condition number of the linear system and averaging out independent
    # noise sources between the two polarisation modes.
    print("\nMethod 5: Photometric stereo - 8-light combined (co + cross)")
    I_8     = np.concatenate([I_cross, I_co], axis=0)
    L8      = np.concatenate([L, L], axis=0)
    ns_8, _ = photometric_stereo(I_8, L8, mask)
    _ps_to_height(ns_8, mask, f"combined_8light_theta{THETA}")

    # ── Method 6: per-channel RGB photometric stereo (cross-polarised) ────────
    # Ink on papyrus may reflect differently in R, G, and B.  Per-channel stereo
    # reveals ink layer geometry that averages out in luminance-based methods.
    print("\nMethod 6: Per-channel RGB photometric stereo (cross-polarised)")
    def _load_channel(path: Path, ch: int) -> np.ndarray:
        # tifffile, not PIL - see the note above _load_gray.  Channel order on
        # disk is RGB, so ch 0/1/2 are R/G/B as the loop below assumes.
        # Reads Stage 1 output, so restore the headroom like _load_gray does.
        return (tifffile.imread(str(path)).astype(np.float32)[..., ch]
                / 65535.0 * np.float32(_stage1_headroom()))

    for ch_idx, ch_name in enumerate(["R", "G", "B"]):
        I_ch = np.stack([
            _load_channel(CAL_OUT / "ncross_cal.tiff", ch_idx),
            _load_channel(CAL_OUT / "scross_cal.tiff", ch_idx),
            _load_channel(CAL_OUT / "ecross_cal.tiff", ch_idx),
            _load_channel(CAL_OUT / "wcross_cal.tiff", ch_idx),
        ], axis=0)
        ns_ch, _ = photometric_stereo(I_ch, L, mask)
        _ps_to_height(ns_ch, mask, f"cross_ps_channel{ch_name}_theta{THETA}")

    print("\nStage 3 complete.")


# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 4 - PREP FOR RENDERING
# ═══════════════════════════════════════════════════════════════════════════════
#
# WHY THIS IS NEEDED:
#   Most real-time renderers require textures whose spatial dimensions are
#   powers of two (512, 1024, 2048 ...).  The scroll was also photographed
#   with a different orientation from the renderer's coordinate frame, so all
#   maps are rotated 180° counter-clockwise (two 90° CCW passes) before export.

def next_pot(n: int) -> int:
    """Smallest power of two >= n  (e.g. 1000 -> 1024)."""
    if n < 1:
        return 1
    return 1 << (n - 1).bit_length()


def spatial_axes(img: np.ndarray) -> tuple[int, int]:
    """
    Return (row_axis, col_axis) for the H and W dimensions.

    tifffile returns arrays in several shapes depending on the file:
      (H, W)       - grayscale
      (H, W, C)    - colour / multi-channel  [last dim ≤ 4]
      (P, H, W)    - multi-page grayscale    [last dim > 4]
      (P, H, W, C) - multi-page colour
    """
    if img.ndim == 2:
        return 0, 1
    if img.ndim == 3:
        return (0, 1) if img.shape[2] <= 4 else (1, 2)
    if img.ndim == 4:
        return 1, 2
    raise ValueError(f"Unsupported array ndim={img.ndim}, shape={img.shape}")


def rotate_ccw90(img: np.ndarray) -> np.ndarray:
    """Rotate 90° counter-clockwise in the spatial plane."""
    row_ax, col_ax = spatial_axes(img)
    return np.rot90(img, k=1, axes=(row_ax, col_ax))


def pad_to_pot(img: np.ndarray) -> np.ndarray:
    """Zero-pad both spatial axes to the next power of two, image centred."""
    row_ax, col_ax = spatial_axes(img)
    h, w           = img.shape[row_ax], img.shape[col_ax]
    pot_h, pot_w   = next_pot(h), next_pot(w)

    if h == pot_h and w == pot_w:
        return img

    pad_h, pad_w = pot_h - h, pot_w - w
    pad_width    = [(0, 0)] * img.ndim
    pad_width[row_ax] = (pad_h // 2, pad_h - pad_h // 2)
    pad_width[col_ax] = (pad_w // 2, pad_w - pad_w // 2)
    return np.pad(img, pad_width, mode="constant", constant_values=0)


def _process_render_file(in_path: Path, out_path: Path, srgb: bool = False) -> None:
    """Encode if it is colour, pad to power-of-two, write to the render folder.

    `srgb` applies the sRGB transfer curve, and is set for the DIFFUSE MAP ONLY.
    glTF defines baseColorTexture as sRGB-encoded and every viewer decodes it on
    load, so a linear diffuse map would come out roughly twice too dark. Every
    other map is data, not colour - normals, height, roughness, specular
    intensity and alpha are all sampled linearly - so encoding them would
    corrupt the values.
    """
    img = tifffile.imread(str(in_path))

    row_ax, col_ax = spatial_axes(img)
    h_in, w_in     = img.shape[row_ax], img.shape[col_ax]

    if srgb:
        if img.dtype != np.uint16:
            raise ValueError(f"{in_path.name}: expected uint16 for sRGB encoding, "
                             f"got {img.dtype}")
        img = (np.clip(cc.srgb_encode(img.astype(np.float64) / 65535.0), 0.0, 1.0)
               * 65535).astype(np.uint16)

    #img = rotate_ccw90(img)   # first 90° CCW
    #img = rotate_ccw90(img)   # second 90° CCW -> 180° total
    img = pad_to_pot(img)

    row_ax2, _ = spatial_axes(img)
    h_out      = img.shape[row_ax2]
    w_out      = img.shape[spatial_axes(img)[1]]

    tifffile.imwrite(str(out_path), img)
    print(f"  {in_path.name:<55} ->  {out_path.name:<25} "
          f"({w_in}×{h_in}  ->  {w_out}×{h_out})  dtype={img.dtype}"
          + ("  [sRGB-encoded]" if srgb else ""))


def run_prep_for_rendering() -> None:
    """Stage 4: rotate and pad all maps for the renderer."""
    print("\n")
    print("  STAGE 4 - PREP FOR RENDERING")
    print("\n")
    print(f"  Maps           : {MAPS_OUT}")
    print(f"  Height maps    : {HM_OUT}")
    print(f"  Alpha mask     : {MASKS_DIR}")
    print(f"  Output         : {RENDER_OUT}\n")

    RENDER_OUT.mkdir(parents=True, exist_ok=True)

    # The 8-light combined height map is the most constrained (8 images,
    # both polarisation states) and is therefore used as the primary height
    # map for rendering.
    #
    # _save_u16 builds filenames via Path.stem.  When the stem contains a
    # decimal (e.g. "theta36.98_weighted_frankot"), Python treats everything
    # after the last dot (".98_weighted_frankot") as the file extension and
    # strips it - so Stage 3 writes "combined_8light_theta36_u16.tiff", not
    # "combined_8light_theta36.98_weighted_frankot_u16.tiff".  Replicating
    # that same Path.stem call here guarantees Stage 4 always finds the file
    # that Stage 3 actually produced, regardless of how THETA is formatted.
    hmap_stem = Path(f"combined_8light_theta{THETA}_weighted_frankot").stem
    hmap_name = hmap_stem + "_u16.tiff"

    # (source, destination, sRGB-encode?) - only the diffuse map is colour.
    render_files = [
        (MASKS_DIR / "AlphaMask.tiff",         RENDER_OUT / "AlphaMask_render.tiff",   False),
        (HM_OUT    / hmap_name,                RENDER_OUT / "HeightMap_render.tiff",   False),
        (MAPS_OUT  / "DiffuseMap_Cal.tiff",    RENDER_OUT / "DiffuseMap_render.tiff",  True),
        (MAPS_OUT  / "NormalMap_Cal.tiff",     RENDER_OUT / "NormalMap_render.tiff",   False),
        (MAPS_OUT  / "SpecularMap_Cal.tiff",   RENDER_OUT / "SpecularMap_render.tiff", False),
        (MAPS_OUT  / "RoughnessMap_Cal.tiff",  RENDER_OUT / "RoughnessMap_render.tiff",False),
    ]

    for in_path, out_path, srgb in render_files:
        if not in_path.exists():
            print(f"  WARNING: {in_path.name} not found - skipping.")
            continue
        _process_render_file(in_path, out_path, srgb=srgb)

    print("\nStage 4 complete.")


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN - run all five stages in sequence
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    print("MODELING PIPELINE")
    print(f"\nApp root       : {APP_ROOT}")
    print(f"Light angle    : {THETA}°")
    print(f"Gaussian sigma : {SMOOTH_SIGMA} px")
    print(f"Mask backend   : {MASK_BACKEND}"
          + (f" / {MASK_MODEL}" if MASK_BACKEND == "rembg" else ""))

    run_alpha_mask()
    run_calibration()
    run_core_maps()
    run_height_maps()
    run_prep_for_rendering()

    print("\n")
    print("  PIPELINE COMPLETE")
    print("\n")
    print(f"  Calibrated images  ->  {CAL_OUT}")
    print(f"  Core maps          ->  {MAPS_OUT}")
    print(f"  Height maps        ->  {HM_OUT}")
    print(f"  Render-ready maps  ->  {RENDER_OUT}")
    print()


if __name__ == "__main__":
    main()
